/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/curved-plane-2.glb -o ./src/components/CurvedPlane2.jsx 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CurvedPlane2(props) {
	const { nodes, materials } = useGLTF("/curved-plane-2.glb");
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Plane.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} />
		</group>
	);
}

useGLTF.preload("/curved-plane-2.glb");
